name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release-mac:
      runs-on: macos-latest
      steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --also=dev
        
      - name: Setup Extra Resources
        run: |
          mkdir -p extra_resources/.platformio/
          mkdir -p extra_resources/yetenek12-library/
          rsync -a yetenek-ide-pio-mac/* extra_resources/.platformio/
          rsync -a yetenek12-library/* extra_resources/yetenek12-library/
          rsync -a ./src/workspace.xml extra_resources/workspace.xml
        shell: bash

      - name: Rebuild App
        run: npm run rebuild-app
        shell: bash
        
      - name: Build App
        run: |
          export GH_TOKEN=${{ secrets.github_token }}
          export CSC_IDENTITY_AUTO_DISCOVERY=false
          npm run build-app
        shell: bash
        
      - name: Release App
        uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: build/**.dmg
